SPONSOR_PROFILE ?= review
SPONSOR_INPUT_PATH ?=
SPONSOR_OUTPUT_DIR ?= out/sponsor
SPONSOR_ARGS ?=

.PHONY: tx-extract ports run-waveform

tx-extract:
	SPONSOR_TARGET=tx-extract SPONSOR_PROFILE="$(SPONSOR_PROFILE)" SPONSOR_INPUT_PATH="$(SPONSOR_INPUT_PATH)" SPONSOR_OUTPUT_DIR="$(SPONSOR_OUTPUT_DIR)" SPONSOR_ARGS="$(SPONSOR_ARGS)" node tools/sponsor-manual-tool.mjs

ports:
	SPONSOR_TARGET=ports SPONSOR_PROFILE="$(SPONSOR_PROFILE)" SPONSOR_INPUT_PATH="$(SPONSOR_INPUT_PATH)" SPONSOR_OUTPUT_DIR="$(SPONSOR_OUTPUT_DIR)" SPONSOR_ARGS="$(SPONSOR_ARGS)" node tools/sponsor-manual-tool.mjs

run-waveform:
	SPONSOR_TARGET=run-waveform SPONSOR_PROFILE="$(SPONSOR_PROFILE)" SPONSOR_INPUT_PATH="$(SPONSOR_INPUT_PATH)" SPONSOR_OUTPUT_DIR="$(SPONSOR_OUTPUT_DIR)" SPONSOR_ARGS="$(SPONSOR_ARGS)" node tools/sponsor-manual-tool.mjs
